- tool/src/webapp/WEB-INF/applicationContext.xml
instead of Spring message loader so we get correct internationalization
> EVALSYS-1305 use ResourceLoaderMessageSource 

- tool/pom.xml
> EVALSYS-1440 poi 3.11

- impl/src/java/org/sakaiproject/evaluation/dao/PreloadDataImpl.java
- impl/src/test/org/sakaiproject/evaluation/dao/EvaluationDaoImplTest.java
Could someone check that the fix for EVALSYS-1031 is the correct one as I'm changing the preload data.
> EVALSYS-1443 Fix failing unit tests.

- api/src/java/org/sakaiproject/evaluation/logic/EvalEmailsLogic.java
- tool/src/java/org/sakaiproject/evaluation/tool/SendEmailsBean.java
- tool/src/webapp/WEB-INF/requestContext.xml
Patch adapted from Matthew Bucket's one to work in trunk.
> EVALSYS-1122 - Manual reminders don't have template variables expanded.

- tool/src/java/org/sakaiproject/evaluation/tool/bundle/messages.properties
- tool/src/java/org/sakaiproject/evaluation/tool/bundle/messages_es_ES.properties
- tool/src/java/org/sakaiproject/evaluation/tool/producers/ReportsViewingProducer.java
- tool/src/java/org/sakaiproject/evaluation/tool/reporting/EvalLikertChartBuilder.java
- tool/src/java/org/sakaiproject/evaluation/tool/reporting/EvalPDFReportBuilder.java
- tool/src/java/org/sakaiproject/evaluation/tool/reporting/PDFReportExporter.java
- tool/src/java/org/sakaiproject/evaluation/tool/reporting/PDFReportExporterIndividual.java
- tool/src/java/org/sakaiproject/evaluation/tool/utils/RenderingUtils.java
- tool/src/test/org/sakaiproject/evaluation/tool/reporting/PDFReportExporterFontSizeTest.java
The PDF export support for individuals is just a copy of the normal export with a could of extra lines, this really should be refactored as it's means you have to make the changes in 2 files.
> EVALSYS-1100 Improvements in weighted means and pdf reports

- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalAdhocGroup.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalAdhocUser.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalAdmin.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalAnswer.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalAssignGroup.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalAssignHierarchy.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalAssignUser.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalConfig.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalEmailProcessingData.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalEmailTemplate.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalEvaluation.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalGroupNodes.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalItem.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalItemGroup.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalLock.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalResponse.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalScale.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalTags.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalTagsMeta.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalTemplate.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalTemplateItem.hbm.xml
- api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalTranslation.hbm.xml
- impl/src/ddl/hibernate.cfg.xml
- impl/src/test/hibernate.cfg.xml
from hibernate.sourceforge.net
> EVALSYS-1449 change hibernate DTD path to www.hibernate.org 

- sakai-evaluation-tool/src/java/org/sakaiproject/evaluation/tool/producers/EvaluationSettingsProducer.java
> EVALSYS-1444 - Null value in EVAL_EVALUATION.ALL_ROLES_PARTICIPATE

- sakai-evaluation-api/src/java/org/sakaiproject/evaluation/constant/EvalConstants.java
- sakai-evaluation-api/src/java/org/sakaiproject/evaluation/constant/EvalEmailConstants.java
- sakai-evaluation-api/src/java/org/sakaiproject/evaluation/logic/EvalSettings.java
- sakai-evaluation-impl/src/java/org/sakaiproject/evaluation/dao/PreloadDataImpl.java
- sakai-evaluation-impl/src/java/org/sakaiproject/evaluation/logic/EvalEmailsLogicImpl.java
- sakai-evaluation-impl/src/java/org/sakaiproject/evaluation/logic/EvalEvaluationServiceImpl.java
- sakai-evaluation-tool/src/java/org/sakaiproject/evaluation/tool/bundle/messages.properties
- sakai-evaluation-tool/src/java/org/sakaiproject/evaluation/tool/producers/AdministrateEmailProducer.java
- sakai-evaluation-tool/src/webapp/content/templates/administrate_email.html
> EVALSYS-1456 - Create a new eval template to send to evaluatees when open

- sakai-evaluation-impl/src/java/org/sakaiproject/evaluation/logic/scheduling/ExportEvaluationReportsImpl.java
> EVALSYS-1453 - Try 2 with some additional error checking, logging and

- sakai-evaluation-impl/src/java/org/sakaiproject/evaluation/logic/scheduling/ExportEvaluationReportsImpl.java
> EVALSYS-1453 - One more fix to switch the search/replace for title

- sakai-evaluation-tool/src/webapp/content/js/evalUtils.js
I feel like this fix of forcing the local jquery to load if it's not defined as well as using the document.getElementById fixes a lot of these issues. You'll still need to probably apply SAK-31332 to get this to work entirely though but I don't have any errors after these.
> EVALSYS-1477 - Datepicker no longer present/working

- sakai-evaluation-tool/pom.xml
https://jira.sakaiproject.org/browse/EVALSYS-1488
poi 3.14
> EVALSYS-1488 poi 3.14

- sakai-evaluation-tool/src/webapp/content/css/evaluation_base.css
'Add rating scale' page non responsive
> EVALSYS-1489

- sakai-evaluation-impl/src/java/org/sakaiproject/evaluation/logic/EvalCommonLogicImpl.java
The previous logic with the foundAll doesn't make any sense. 
Okay added second commit I found in EVALSYS-1472... @bjones86 can you review the second commit (b5b22a7)?
> EVALSYS-1496 fixing incorrect logic around email sending

- sakai-evaluation-tool/src/java/org/sakaiproject/evaluation/tool/producers/EvaluationAssignProducer.java
https://jira.sakaiproject.org/browse/EVALSYS-1497
> EVALSYS-1497: page height doesnt resize when collapsed sections expanded

- sakai-evaluation-api/src/java/org/sakaiproject/evaluation/dao/hbm/EvalEvaluation.hbm.xml
Shorten name for Oracle (reported and tested by Jeb Miller)
> EVALSYS-1403 Shorten FK name for Oracle

- sakai-evaluation-tool/src/java/org/sakaiproject/evaluation/tool/reporting/EvalPDFReportBuilder.java
- sakai-evaluation-tool/src/java/org/sakaiproject/evaluation/tool/reporting/PDFReportExporter.java
As requested by Brian Jones, PR made against master.
PR simply uncomments code, and overloads a single method.
> EVALSYS-1520: re-enabled lecturer names during pdf reporting

- sakai-evaluation-tool/src/java/org/sakaiproject/evaluation/tool/renderers/NavBarRenderer.java
https://jira.sakaiproject.org/browse/EVALSYS-1522
> EVALSYS-1522: error after survey with NavBarRenderer (probably anonymous) via URL

- sakai-evaluation-tool/src/java/org/sakaiproject/evaluation/tool/reporting/XLSReportExporter.java
font.setBoldweight(Font.BOLDWEIGHT_BOLD); => font.setBold(true);
> EVALSYS-1529 Poi deprecated :

- sakai-evaluation-impl/src/java/org/sakaiproject/evaluation/logic/EvalEmailsLogicImpl.java
> EVALSYS-1538 - Emails are sent to all groups instead of the selected group

- sakai-evaluation-tool/src/java/org/sakaiproject/evaluation/tool/producers/ControlEvaluationsProducer.java
- sakai-evaluation-tool/src/java/org/sakaiproject/evaluation/tool/renderers/AdminBoxRenderer.java
View only evalsys admin doesn't seem to work
> EVALSYS-1531 - View only evalsys admin doesn't seem to work

- sakai-evaluation-impl/src/java/org/sakaiproject/evaluation/logic/externals/EvalExternalLogicImpl.java
- sakai-evaluation-pack/src/webapp/WEB-INF/external-logic.xml
scheduledInvocationManager.createDelayedInvocation(Time @deprecated =>
scheduledInvocationManager.createDelayedInvocation(Date.toInstant()
> EVALSYS-1540

- sakai-evaluation-impl/src/java/org/sakaiproject/evaluation/logic/EvalEvaluationSetupServiceImpl.java
- sakai-evaluation-pack/src/webapp/WEB-INF/components.xml
https://jira.sakaiproject.org/browse/EVALSYS-1545
> EVALSYS-1545: You can't select a node of the hierarchy if the evaluation is section aware

- sakai-evaluation-impl/src/java/org/sakaiproject/evaluation/logic/EvalCommonLogicImpl.java
- sakai-evaluation-tool/src/java/org/sakaiproject/evaluation/tool/producers/EvaluationNotificationsProducer.java
- sakai-evaluation-tool/src/java/org/sakaiproject/evaluation/tool/producers/EvaluationRespondersProducer.java
- sakai-evaluation-tool/src/java/org/sakaiproject/evaluation/tool/producers/EvaluationSettingsProducer.java
Controlling one NPE for not logged users and cleaning some whitespaces too
> EVALSYS-1557 Adding security checks for some Evaluation producers

- sakai-evaluation-tool/src/java/org/sakaiproject/evaluation/tool/producers/ModifyScaleProducer.java
> EVALSYS-1578 ability to add and edit new scale without ClassCastException

- pom.xml
- sakai-evaluation-impl/src/java/org/sakaiproject/evaluation/dao/EvaluationDaoImpl.java
- sakai-evaluation-impl/src/test/hibernate-test.xml
https://jira.sakaiproject.org/browse/EVALSYS-1597
> EVALSYS-1597 Migrate away from positional style hql queries
